// Generated by gencpp from file kuka_kickass_kalman/Obs.msg
// DO NOT EDIT!


#ifndef KUKA_KICKASS_KALMAN_MESSAGE_OBS_H
#define KUKA_KICKASS_KALMAN_MESSAGE_OBS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuka_kickass_kalman
{
template <class ContainerAllocator>
struct Obs_
{
  typedef Obs_<ContainerAllocator> Type;

  Obs_()
    : z1(0.0)
    , z2(0.0)  {
    }
  Obs_(const ContainerAllocator& _alloc)
    : z1(0.0)
    , z2(0.0)  {
  (void)_alloc;
    }



   typedef double _z1_type;
  _z1_type z1;

   typedef double _z2_type;
  _z2_type z2;





  typedef boost::shared_ptr< ::kuka_kickass_kalman::Obs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuka_kickass_kalman::Obs_<ContainerAllocator> const> ConstPtr;

}; // struct Obs_

typedef ::kuka_kickass_kalman::Obs_<std::allocator<void> > Obs;

typedef boost::shared_ptr< ::kuka_kickass_kalman::Obs > ObsPtr;
typedef boost::shared_ptr< ::kuka_kickass_kalman::Obs const> ObsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuka_kickass_kalman::Obs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kuka_kickass_kalman

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kuka_kickass_kalman': ['/home/parallels/Extended-Kalman-ROS/src/kuka_kickass_kalman/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuka_kickass_kalman::Obs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuka_kickass_kalman::Obs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuka_kickass_kalman::Obs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb1f7128c63dfa90147251ef0b5eeab7";
  }

  static const char* value(const ::kuka_kickass_kalman::Obs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb1f7128c63dfa90ULL;
  static const uint64_t static_value2 = 0x147251ef0b5eeab7ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuka_kickass_kalman/Obs";
  }

  static const char* value(const ::kuka_kickass_kalman::Obs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 z1\n\
float64 z2\n\
";
  }

  static const char* value(const ::kuka_kickass_kalman::Obs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.z1);
      stream.next(m.z2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuka_kickass_kalman::Obs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuka_kickass_kalman::Obs_<ContainerAllocator>& v)
  {
    s << indent << "z1: ";
    Printer<double>::stream(s, indent + "  ", v.z1);
    s << indent << "z2: ";
    Printer<double>::stream(s, indent + "  ", v.z2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUKA_KICKASS_KALMAN_MESSAGE_OBS_H
